---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
        - name: app-cont
          image: shaikmustafa/anath:v1
          ports:
            - containerPort: 5454   #using 5454

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: LoadBalancer
  selector:
    app: food
  ports:
    - port: 80
      targetPort: 5454     #targetport=containerport
      protocol: TCP
